### ISSUE TITLE
Question on node comunications and signal server

### ISSUE THREAD

**Issue by fsvieira** [RAN3D/foglet-core#27]
Hi, 

I am experimenting doing a p2p queue (https://github.com/fsvieira/p2pqueue) its still on proof-of-concept phase, I still need to work on stats. 

I have a question, can I send a message from node A to node Z, if they are not neighbors something like this, 
A -> B -> ... -> X, Z , where B ... X nodes that connect A to Z, how this works on foglet-core ?

Another question is that I am getting same node but with suffix -I and -O, from what I understand they are the same but some are out view and in view, the problem is that I get both when I call  getNeighbours(limit), for example If I have only two nodes, and request a limit=4 I get same id with id-I and id-O , I would like to get only one id because when I send a message to all the neighbors on the list I am duplicating messages sent. Or is this feature ? If network changes they will still be able to send message ?

Another question, I saw this https://ran3d.github.io/foglet-core/class/src/fprotocol/answer-queue.js~AnswerQueue.html on the docs but  I don't understand it, what is it for and how to use it ? 

An issue that I had following the docs was using the floget-scripts, it doenst work because signal server version is to old. So I had to install "foglet-signaling-server": "^1.0.3" directly. 

Thanks.

**Comment by folkvir** [comment]
foglet-core allows you to use cyclon or spray (not stable) as default Random Peer sampling protocols as a first layer for managing your network connections. You're also able to create your own network protocol management if you want. 

In this library only broadcast routing is performed. If you want to make your own communication protocol aka A to Z in a connected graph, then you must implement a routing mechanism in your application.
A simple  and costly way would be to use the broadcast primitive and listening for your desired event. But if you want a more fine-grained, I suggest you to implement a routing mechanism on top of each "Foglet" by using "-O" IDs.
The -O Ids are IDs available on your OUT view. Only the OUT view can be manipulated. Due to the fact that WebRTC is bidirectional you'll be able to send data on both view by using`*-I` and `*-O` IDs 
If you want to communicate by using the Unicast primitive then you have different case to keep in mind,

Imagine this scenario:
* `A -> B -> C`, if A sends a message, then by transitivity it can reach C.
* Now if C sends a message, none of the other peer will receive the message if C makes usage of the `-O` ID because C has no neighbor in its OUT view. But you know that someone is connected to you because of your `-I`ID in your IN view. So you can sends data by using the `-I` ID.

https://ran3d.github.io/foglet-core/class/src/fprotocol/answer-queue.js~AnswerQueue.html is used internally for implementing a custom protocol for sharing data. But it is very experimental. And If in the future I have time to continue the development then I will remove this part.

**Comment by folkvir** [comment]
Glad to see that the signaling server is still working :)
Like I said if I have time to continue this lib, I will make a complete rework by including the signaling server, and the underlying libraries. There is already a beginning of this in the branches and in the ran3d organization but not anymore maintained.

Can I ask why are you using the foglet-core library? perhaps another maintained library could fit your needs in the current ecosystem.

**Comment by fsvieira** [comment]
Hi, thank you for your answer.

I am using foglet-core for exploring the possibility of using p2p distributed computing on another experimental project https://github.com/fsvieira/zebradb-core . It would be fun if a computing node could be easily created by just opening a url in the browser.

But neither zebra-core is full working or running in parallel yet, I am redesigning the project so I thought  about trying to make it distributed.

Concluding I am using foglet-core just for fun.

What I like about foglet-core is that is not so low level that I would have to implement the network mesh myself but its not high level that abstracts completely the network structure.

I understand that the project is not actively maintained anymore, and I have no expectation that it would be updated in the future, 
I will keep exploring and will see where it leads me.

Thanks, I do appreciate that you had take the time to answer me.

**Comment by folkvir** [comment]
>  It would be fun if a computing node could be easily created by just opening a url in the browser.

Yes, it was the goal of this lib. Just start a server hosting your app, when clicking on the url it connects the node on the network of participant. The major advantage is that this server connection is just made once, not for all connections but the only the first one. Then, all WebRTC offers are transferred by connected peers.

Thank you for using this just as a test example. +1

I suggest you in your code if want to be aware of all the communications problem to just create a `receive(message)` function. With this you can plug any P2P protocol and manage messages like you want. You can do the same thing for sending messages with `send(message)`.
